#!/usr/bin/env bash

########################################################################
# This install script will setup your development dependencies on OS X
# or Ubuntu. Ubuntu 16.04 is the only tested version.
#
# Usage: scripts/setup
########################################################################

YELLOW='\033[1;33m'
NC='\033[0m'

_current_dir=$(cd "${BASH_SOURCE%/*}" && pwd)
source "$_current_dir/lib/setup/path-support.sh"

source_lib "output.sh"
source_lib "packages.sh"
source_lib "platform.sh"
source_lib "installers.sh"

exit_unless_os_supported

load_rvm_if_available

####
setup_header "Installing requirements..."

if ! program_exists "nix"; then
  if is_macos; then
    touch -a $HOME/.bash_profile
  elif is_linux; then
    touch -a $HOME/.bashrc
  fi

  sh <(curl https://nixos.org/nix/install) --no-daemon && \
    echo -e "${YELLOW}*******************************************************************************************************"
    echo "The Nix package manager was successfully installed. Please do the following:"
    echo "  - open a new terminal"
    echo "  - type 'make shell' in the terminal"
    echo "  - run 'make setup' again"
  echo -e "*********************************************************************************************************${NC}"
  exit
fi
install_nsis
install_react_native_cli
install_android_sdk
install_android_ndk
install_cocoapods

####
echo && setup_header "Installing dependencies..."

dependency_setup make prepare-mobile

setup_complete
